erase *.obj
erase metaverseserver.exe
erase metaverseclient.exe
erase rendererglutsplit.exe
erase dbinterface.exe
erase serverfileagent.exe
erase clientfileagent.exe
erase scriptingengineprotlua.exe
erase scriptingengineprot2.exe
erase odephysicsengine.dll
